version: '3'
services:
  ###
  # services
  ###
  postgres:
    image: postgres:10.9
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - 'env'
    ports:
        - "5432:5432"

  app:
    build: ./app
    command: /bin/bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
        - ./app:/app
    ports:
        - "3000:3000"
    env_file:
        - 'env'
    depends_on:
        - postgres

    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8



volumes:
  postgres:
